universe = docker
docker_image = chaahatjain/jani_in_python:latest

executable = /usr/bin/python3
arguments = test_gurobi.py

getenv = HOME
+WantGPUHomeMounted = true
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = test_gurobi.py, /home/atml_team041/condor_tutorial/gurobi.lic

requirements = UidDomain == "cs.uni-saarland.de"

request_GPUs = 0
request_CPUs = 1
request_memory = 2G

environment = "GRB_LICENSE_FILE=gurobi.lic"

output = logs/test_gurobi.out
error = logs/test_gurobi.err
log = logs/test_gurobi.log

queue